---
- name: reload systemd configuration
  command: systemctl daemon-reload

- name: restart cert_agent
  service: name=cert_agent state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

